import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('Agent Composer controls', () => {
  test('Given a selected model When the composer footer renders Then model and reasoning share one compact control', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const modelSelectorSource = readFileSync(resolve(import.meta.dir, '../chat/ModelSelector.tsx'), 'utf8')
    const styles = readFileSync(resolve(import.meta.dir, '../../styles/globals.css'), 'utf8')

    expect(source).toContain("'model-effort-trigger flex h-[26px]")
    expect(source).toContain('modelName={composerModelName}')
    expect(source).toContain('modelLogo={composerModelLogo}')
    expect(source).toContain('channelName={composerChannelName}')
    expect(source).toContain('const composerChannelName = selectedModelOption?.channelName')
    expect(source).toContain('<Tooltip open={open || !channelName ? false : undefined}>')
    expect(source).toContain('<TooltipContent side="top">渠道：{channelName}</TooltipContent>')
    expect(source).toContain('onOpenModelSelector={() => store.set(modelSelectorOpenAtom, true)}')
    expect(source).toContain('trackClassName="h-[26px] bg-muted"')
    expect(source).toContain("rangeClassName={cn('agent-effort-range', isMaxLevel && 'agent-effort-range-max')}")
    expect(source).toContain("'agent-effort-thumb z-20 size-[30px] border-0 bg-white shadow-none'")
    expect(source).toContain("isMaxLevel && 'agent-effort-thumb-max'")
    expect(source).not.toContain('#3f83f8')
    expect(styles).toContain('--effort-slider-from: #ff8a3d')
    expect(styles).toContain('--effort-slider-via: #ff5d48')
    expect(styles).toContain('--effort-slider-to: #f43f4f')
    expect(styles).toContain('var(--effort-slider-from)')
    expect(styles).not.toContain('.agent-effort-range {\n  position: relative;')
    expect(styles).toContain('@keyframes agent-effort-max-shimmer')
    expect(styles).toContain('@keyframes agent-effort-max-enter')
    expect(styles).toContain('@keyframes agent-effort-max-glow')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(styles).toContain('.agent-effort-range-max::after,')
    expect(styles).toContain('.agent-effort-thumb-max::after')
    expect(source).toContain('onValueChange={([position]) => setDraftSliderPosition(position ?? sliderPosition)}')
    expect(source).toContain('onValueCommit={([position]) => {')
    expect(source).not.toContain('onValueChange={([position]) => codexConfig.onThinkingLevelChange')
    expect(source).toContain('<span className="shrink-0 text-xs text-muted-foreground">模型</span>')
    expect(source).toContain('className="ml-auto min-w-0 truncate text-right text-xs font-medium text-foreground"')
    expect(source).toContain('<span className="text-xs font-medium text-foreground/80">推理强度</span>')
    expect(source).toContain('hideTrigger')
    expect(modelSelectorSource).toContain('{!hideTrigger && (')
  })

  test('renders one prioritized modern rail above the message composer', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const stackIndex = source.indexOf('data-agent-composer-stack="true"')
    const targetChooserIndex = source.indexOf('<AgentSessionTargetChooser', stackIndex)
    const activeWorktreeRailIndex = source.indexOf("composerActionRailKind === 'worktree_active'", stackIndex)
    const issueRailIndex = source.indexOf("composerActionRailKind === 'agent_issue'", stackIndex)
    const runtimeRailIndex = source.indexOf("composerActionRailKind === 'agent_runtime'", stackIndex)
    const summaryRailIndex = source.indexOf("composerActionRailKind === 'agent_summary'", stackIndex)
    const channelRailIndex = source.indexOf("composerActionRailKind === 'channel_setup'", stackIndex)
    const settledWorktreeRailIndex = source.indexOf("composerActionRailKind === 'worktree_settled'", stackIndex)
    const surfaceIndex = source.indexOf('data-agent-composer-surface="true"', stackIndex)

    expect(stackIndex).toBeGreaterThan(-1)
    expect(targetChooserIndex).toBeGreaterThan(stackIndex)
    expect(issueRailIndex).toBeGreaterThan(targetChooserIndex)
    expect(runtimeRailIndex).toBeGreaterThan(issueRailIndex)
    expect(activeWorktreeRailIndex).toBeGreaterThan(runtimeRailIndex)
    expect(summaryRailIndex).toBeGreaterThan(activeWorktreeRailIndex)
    expect(channelRailIndex).toBeGreaterThan(summaryRailIndex)
    expect(settledWorktreeRailIndex).toBeGreaterThan(channelRailIndex)
    expect(surfaceIndex).toBeGreaterThan(settledWorktreeRailIndex)
    expect(source).toContain('resolveComposerActionRailKind({')
    expect(source).toContain('hasUrgentWorktreeAction: worktreeRailPriority === \'urgent\',')
    expect(source).toContain('hasActiveWorktreeAction: worktreeRailPriority === \'active\',')
    expect(source).toContain('hasSettledWorktreeAction: worktreeRailPriority === \'settled\',')
    expect(source).toContain('preflightStatus: sessionTargetState.preflight?.status,')
    expect(source).toContain("preflightBlockedReason: sessionTargetState.preflight?.status === 'blocked'")
    expect(source).toContain('checkoutPhase: sessionTargetState.snapshot?.checkout.phase,')
    const runtimeRailSource = readFileSync(resolve(import.meta.dir, 'AgentRuntimeActionRail.tsx'), 'utf8')
    expect(runtimeRailSource).toContain("dataKind=\"agent_runtime\"")
    expect(source).toContain("dataKind=\"agent_summary\"")
    expect(source).toContain("dataKind=\"channel_setup\"")
    expect(source).toContain("window.electronAPI.retryAgentNow(sessionId)")
    expect(source).toContain("streamState?.retrying?.phase === 'scheduled'")
    expect(source).toContain("retryNowPending ? '正在重试…' : '立即重试'")
    const messagesSource = readFileSync(resolve(import.meta.dir, 'AgentMessages.tsx'), 'utf8')
    expect(messagesSource).toContain("retrying.phase === 'scheduled' && onRetryNow")
    expect(messagesSource).toContain("retryNowPending ? '正在重试…' : '立即重试'")
  })

  test('isolates the elapsed timer and smoothed output rate inside the small runtime rail subtree', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const runtimeRailSource = readFileSync(resolve(import.meta.dir, 'AgentRuntimeActionRail.tsx'), 'utf8')
    const telemetrySource = readFileSync(resolve(import.meta.dir, 'agent-runtime-telemetry.ts'), 'utf8')

    expect(source).not.toContain('useAgentRuntimeTelemetry({')
    expect(source).toContain('<AgentRuntimeActionRail')
    expect(source).toContain('visible={composerActionRailKind === \'agent_runtime\'}')
    expect(source).toContain('onTelemetry={runtimeRailState.captureTelemetry}')
    expect(source).toContain('useAgentRuntimeRailState({')
    expect(source).toContain('enabled: useModernComposerRail,')
    expect(source).toContain('scopeKey: sessionId,')
    expect(source).toContain('hasAgentSummary: runtimeSummary !== null')
    expect(source).toContain('calculateAgentSessionUsage(persistedSDKMessages)')
    expect(runtimeRailSource).toContain('useAgentRuntimeTelemetry({')
    expect(runtimeRailSource).toContain('runtimeTelemetry.inputTokens !== null')
    expect(runtimeRailSource).toContain('runtimeTelemetry.outputTokens !== null')
    expect(runtimeRailSource).toContain('runtimeTelemetry.outputTokensEstimated')
    expect(runtimeRailSource).toContain('formatAgentUsageTokens(runtimeTelemetry.inputTokens)')
    expect(runtimeRailSource).toContain('formatAgentUsageTokens(runtimeTelemetry.outputTokens)')
    expect(runtimeRailSource).toContain('agent-runtime-output-tokens')
    expect(runtimeRailSource).toContain('runtimeTelemetry.tokensPerSecond !== null')
    expect(runtimeRailSource).toContain('composer-runtime-rate')
    expect(runtimeRailSource).toContain('text-sky-700/80')
    expect(runtimeRailSource).toContain('dark:text-sky-300/75')
    expect(runtimeRailSource).toContain('text-emerald-700/80')
    expect(runtimeRailSource).toContain('dark:text-emerald-300/75')
    expect(runtimeRailSource).toContain('text-violet-700/80')
    expect(runtimeRailSource).toContain('dark:text-violet-300/75')
    expect(runtimeRailSource).toContain('composer-runtime-detail')
    expect(runtimeRailSource).toContain('contentClassName="max-w-[48%] flex-none"')
    expect(runtimeRailSource).not.toContain('title=')
    expect(runtimeRailSource).not.toContain('contentTitle=')
    expect(runtimeRailSource).not.toContain('runtimeStatusTitle')
    expect(telemetrySource).toContain('window.setInterval(() => setClock(Date.now()), 500)')
  })

  test('deduplicates only the modern message runtime status and keeps the Composer stop control', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const messagesSource = readFileSync(resolve(import.meta.dir, 'AgentMessages.tsx'), 'utf8')

    expect(source).toContain('showRunningIndicator={!runtimeRailOwnsRunningIndicator}')
    expect(source).toContain('const runtimeRailOwnsRunningIndicator = composerRailOwnsRunningIndicator(composerActionRailKind)')
    const runtimeRailSource = readFileSync(resolve(import.meta.dir, 'AgentRuntimeActionRail.tsx'), 'utf8')
    expect(runtimeRailSource).toContain('icon={<RotatingAgentActivityOrb states={AGENT_RUNNING_ORB_STATES} size={20}')
    expect(source).not.toContain('icon={<Loader2')
    expect(source).not.toContain('composerRailOwnsStopAction')
    expect(source).not.toContain('composer-stop-control-placeholder')
    expect(source).toContain('{stopControl}')
    expect(source).toContain('data-testid="stop-button"')
    expect(messagesSource).toContain('showRunningIndicator?: boolean')
    expect(messagesSource).toContain('showRunningIndicator = true,')
    expect(messagesSource).toContain('streaming && showRunningIndicator && <AgentRunningIndicator')

    expect(runtimeRailSource).not.toContain('onClick={handleStop}')
    expect(runtimeRailSource).not.toContain('停止')
  })

  test('animates only the modern runtime title and respects reduced motion', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const styles = readFileSync(resolve(import.meta.dir, '../../styles/globals.css'), 'utf8')

    const runtimeRailSource = readFileSync(resolve(import.meta.dir, 'AgentRuntimeActionRail.tsx'), 'utf8')
    expect(runtimeRailSource).toContain('className="composer-runtime-title inline-block whitespace-nowrap font-medium">Domi is working…</span>')
    expect(runtimeRailSource.match(/composer-runtime-title/g)?.length).toBe(1)
    const titleRuleStart = styles.indexOf('[data-composer-action-rail="agent_runtime"] .composer-runtime-title')
    const titleRuleEnd = styles.indexOf('\n}', titleRuleStart)
    const titleRule = styles.slice(titleRuleStart, titleRuleEnd)
    expect(titleRuleStart).toBeGreaterThan(-1)
    expect(titleRule).toContain('hsl(var(--foreground)')
    expect(titleRule).toContain('hsl(var(--primary)')
    expect(titleRule).toContain('background-clip: text')
    expect(titleRule).toContain('animation: composer-runtime-title-shimmer 2.8s ease-in-out infinite')
    expect(titleRule).not.toContain('#')
    expect(styles).toContain('@keyframes composer-runtime-title-shimmer')
    expect(styles).toContain('@media (prefers-reduced-motion: reduce)')
    expect(styles).toContain('-webkit-text-fill-color: currentColor')
    expect(styles).toContain('animation: none')
  })

  test('keeps runtime details visible and the completed summary dismissible without collapse controls', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const telemetrySource = readFileSync(resolve(import.meta.dir, 'agent-runtime-telemetry.ts'), 'utf8')
    const railSource = readFileSync(resolve(import.meta.dir, 'ComposerActionRail.tsx'), 'utf8')

    expect(source).toContain('dataTestId="agent-runtime-summary-rail"')
    expect(source).toContain('Run completed')
    expect(source).toContain('runtimeRailState.dismissSummary')
    expect(source).toContain('关闭本轮摘要')
    expect(source).toContain('runtimeSummary.inputTokens !== null')
    expect(source).toContain('runtimeSummary.outputTokensEstimated')
    expect(source).toContain('formatAgentUsageTokens(runtimeSummary.inputTokens)')
    expect(source).toContain('formatAgentUsageTokens(runtimeSummary.outputTokens)')
    expect(source).toContain('text-sky-700/80')
    expect(source).toContain('dark:text-sky-300/75')
    expect(source).toContain('text-emerald-700/80')
    expect(source).toContain('dark:text-emerald-300/75')
    expect(source).toContain('contentClassName="max-w-[36%] flex-none"')
    expect(source).not.toContain('contentTitle="Run completed · Run summary"')
    expect(source).not.toContain('runtimeRailState.collapsed')
    expect(source).not.toContain('runtimeRailState.toggleCollapsed')
    expect(source).not.toContain('收起运行信息')
    expect(source).not.toContain('收起本轮摘要')
    expect(telemetrySource).not.toContain('toggle_collapsed')
    expect(telemetrySource).not.toContain('toggleCollapsed')
    expect(telemetrySource).not.toContain('collapsed:')
    expect(railSource).not.toContain('data-composer-action-rail-collapsed')
  })

  test('does not expose browser-native tooltips in the composer status region', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')
    const railSource = readFileSync(resolve(import.meta.dir, 'ComposerActionRail.tsx'), 'utf8')
    const runtimeRailSource = readFileSync(resolve(import.meta.dir, 'AgentRuntimeActionRail.tsx'), 'utf8')
    const targetSource = readFileSync(resolve(import.meta.dir, 'SessionTargetControl.tsx'), 'utf8')
    const worktreeStatusSource = readFileSync(resolve(import.meta.dir, 'worktree-review/WorktreeReviewStatus.tsx'), 'utf8')
    const stackIndex = source.indexOf('data-agent-composer-stack="true"')
    const surfaceIndex = source.indexOf('data-agent-composer-surface="true"', stackIndex)
    const statusRegion = source.slice(stackIndex, surfaceIndex)

    expect(stackIndex).toBeGreaterThan(-1)
    expect(surfaceIndex).toBeGreaterThan(stackIndex)
    expect(statusRegion).not.toContain('title=')
    expect(runtimeRailSource).not.toContain('title=')
    expect(targetSource).not.toContain('title=')
    expect(worktreeStatusSource).not.toContain('title=')
    expect(railSource).not.toContain('contentTitle')
    expect(railSource).not.toContain('title=')
    expect(statusRegion).toContain('aria-label="关闭本轮摘要"')
  })

  test('keeps classic and terminal channel and Worktree statuses inside the composer', () => {
    const source = readFileSync(resolve(import.meta.dir, 'AgentView.tsx'), 'utf8')

    expect(source).toContain("const useModernComposerRail = interfaceVariant !== 'classic' && themeStyle !== 'terminal-dark'")
    expect(source).toContain('showRunningIndicator={!runtimeRailOwnsRunningIndicator}')
    expect(source).toContain('{!useModernComposerRail && <WorktreeReviewStatus sessionId={sessionId} legacySurface />}')
    expect(source).toContain('{!useModernComposerRail && (!agentChannelId || !hasAvailableModel) && (')
    expect(source).toContain('sessionUsage={sessionUsage}')

    const statusSource = readFileSync(resolve(import.meta.dir, 'worktree-review/WorktreeReviewStatus.tsx'), 'utf8')
    expect(statusSource).toContain("'legacy-worktree-review-status mx-3 mt-2 rounded-md border-blue-500/20 bg-blue-500/5'")
  })

  test('keeps the modern metadata rail transparent while sharing the composer radius token', () => {
    const styles = readFileSync(resolve(import.meta.dir, '../../styles/globals.css'), 'utf8')
    const railSource = readFileSync(resolve(import.meta.dir, 'ComposerActionRail.tsx'), 'utf8')
    const railRuleStart = styles.indexOf(':root:not(.ui-classic):not(.theme-terminal-dark) .composer-action-rail')
    const railRuleEnd = styles.indexOf('}', railRuleStart)
    const railRule = styles.slice(railRuleStart, railRuleEnd)
    const composerRuleStart = styles.indexOf(':root:not(.ui-classic) .agent-composer-surface')
    const composerRuleEnd = styles.indexOf('}', composerRuleStart)
    const composerRule = styles.slice(composerRuleStart, composerRuleEnd)

    expect(railRuleStart).toBeGreaterThan(-1)
    expect(railRule).toContain('border-radius: var(--radius-lg)')
    expect(railRule).toContain('min-height: 2.25rem')
    expect(railRule).toContain('margin: 0')
    expect(railRule).toContain('border-color: transparent')
    expect(railRule).toContain('box-shadow: none')
    expect(railSource).toContain('bg-transparent')
    expect(railRule).not.toContain('background-color: hsl(var(--muted)')
    expect(styles).not.toContain('[data-input-mode] > div:first-child')
    expect(styles).toContain('[data-input-mode="chat"] > div:first-child')
    expect(styles).toContain('[data-input-mode="agent"] > [data-composer-action-rail="agent_runtime"]')
    expect(styles).toContain('[data-input-mode="agent"] > [data-composer-action-rail="agent_summary"]')
    expect(styles).toContain('[data-input-mode="agent"] > [data-composer-action-rail="worktree_active"]')
    expect(styles).toContain('[data-input-mode="agent"] > [data-composer-action-rail="worktree_settled"]')
    expect(styles).toContain('[data-input-mode="agent"] > [data-session-target-chooser="true"]')
    expect(styles).toContain('background-color: transparent !important;')
    expect(styles).toContain('border-color: transparent !important;')
    expect(styles).toContain('box-shadow: none !important;')
    expect(composerRule).toContain('border-radius: var(--radius-lg)')
  })
})
